repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5191f112dfd133e97acba8c2162c37d8613cf54b
    hooks:
      - id: check-yaml
        exclude: ^(conda\.recipe/meta\.yaml|conda_build/templates/.*\.yaml|docs/click/meta\.yaml|conda/meta\.yaml|conda/construct.yaml)
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/hakancelikdev/unimport
    rev: 33ead41ee30f1d323a9c2fcfd0114297efbbc4d5
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]
  # - repo: https://github.com/pycqa/isort
  #   rev: 03a9949368bc8ce115a8ff9ce7f4904def9df721
  #   hooks:
  #     - id: isort
  #       files: gdsfactory/.*
  #       args: [--profile, black, --filter-files]

  - repo: https://github.com/psf/black
    rev: d4ff985853c8d140d73b9d362604deedb41eb20e
    hooks:
      - id: black

  # - repo: https://github.com/omnilib/ufmt
  #   rev: v2.0.0b1
  #   hooks:
  #     - id: ufmt
  - repo: https://github.com/asottile/blacken-docs
    rev: 79ef671d15161b9dbc16ac3760086b5222836583
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]
  # - repo: https://github.com/pycqa/flake8
  #   rev: 33e1c55853fbcc454a2343b9b61a0e715a2f74a4
  #   hooks:
  #     - id: flake8
  #       entry: pflake8
  #       additional_dependencies: [flake8-docstrings, pyproject-flake8]

  - repo: https://github.com/kynan/nbstripout
    rev: 1185a8d25bb45ada13f64d9591c14d81d69206bc
    hooks:
      - id: nbstripout
        files: .ipynb

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: 97ed6fb3cf2e650d4f762ba231c3f04c41797710
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py37-plus, --keep-runtime-typing]

  - repo: https://github.com/codespell-project/codespell
    rev: 3511fcd9b57e167b2bb17fd07c680eaf9befa4b2
    hooks:
      - id: codespell
        args: ["-L TE,TE/TM,te,ba,FPR,fpr_spacing,ro,nd,donot,schem"]

  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: 98854f809ca9d0e235c0bd5c0ad5e986e02120a4
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/PyCQA/bandit
    rev: 91c4d979550888c8d190898279bfdb0af732791e
    hooks:
      - id: bandit
        args: [--exit-zero]
        # ignore all tests, not just tests data
        exclude: ^tests/
  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.14.1
  #   hooks:
  #     - id: pylint
  #       args: [--exit-zero]
  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  #   rev: 6565d773ca281682d7062d4c0be74538cc474cc9
  #   hooks:
  #     - id: pretty-format-java
  #       args: [--autofix]
  #     - id: pretty-format-kotlin
  #       args: [--autofix]
  #     - id: pretty-format-yaml
  #       args: [--autofix, --indent, "2"]
  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.21.0 # or higher tag
  #   hooks:
  #       - id: yamllint
  #         args: [--format, parsable, --strict]
  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.1.0 # or specific tag
  #   hooks:
  #       - id: yamlfmt
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/fixtures)
  #       additional_dependencies:
  #         - "pydantic"
  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: "6.2.2"
  #   hooks:
  #     - id: pydocstyle
  #       additional_dependencies: ["pydocstyle[toml]"]
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 220dacf44e6cc234b8ef87863a31ff9d46dad920
    hooks:
      - id: nbqa-black
        additional_dependencies: [jupytext, black] # optional, only if you're using Jupytext
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
      # - id: nbqa-flake8
      # - id: nbqa-isort
      #   args: ["--float-to-top"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.221"
    hooks:
      - id: ruff
        args: ["--force-exclude"]
