{% set data = load_setup_py_data() %}

package:
  name: albumentations
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install 

requirements:
  build:
    - python
    - numpy

  run:
    - python>=3.7
    - numpy


about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
