package:
  name: gdsfactory
  version: 3.6.7

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy

  run:
    - python>=3.7
    - numpy

about:
  home: https://github.com/gdsfactory/gdsfactory
  license: MIT
summary: python libraries to generate GDS layouts
