rule waveguide_MEEP:
    container:
      "docker://joamatab/gdsfactory:latest"
    output: filepath = "/home/simbil/debugging/snakemake_test.csv"
    shell:
      r"""
      python -c "import gdsfactory as gf
import gdsfactory.simulation.gmeep as gm
c = gf.components.straight(length=5)
df = gm.write_sparameters_meep_mpi(c,
                                resolution=20,
                                filepath='{output.filepath}',
                                dirpath='/home/simbil/debugging/',
                                cores=2,)
"
      """
