# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "gdsfactory"
author: gdsfactory
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: on

latex:
  latex_engine: pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use sphinx-jupyterbook-latex for pdf builds as default

# Add a bibtex file so that we can create citations

html:
  favicon: favicon.ico
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://gdsfactory.github.io/gdsfactory/

# Information about where the book exists on the web
repository:
  url: https://github.com/gdsfactory/gdsfactory # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.autodoc.typehints"
  config:
    #autodoc_typehints: description
    autodoc_type_aliases:
      "Array": "Array"
      "Int": "Int"
      "Float": "Float"
      "ComplexFloat": "ComplexFloat"
      "Settings": "Settings"
      "SDict": "SDict"
      "SCoo": "SCoo"
      "SDense": "SDense"
      "SType": "SType"
      "Model": "Model"
      "ModelFactory": "ModelFactory"
      "GeneralModel": "GeneralModel"
      "Models": "Models"
      "Instance": "Instance"
      "GeneralInstance": "GeneralInstance"
      "Instances": "Instances"
      "Netlist": "Netlist"
      "LogicalNetlist": "LogicalNetlist"

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org/v2/gh/gdsfactory/gdsfactory/HEAD"
  colab_url: "https://colab.research.google.com"
